package bladequest.world;

public enum States {
	GS_WORLDMOVEMENT,
	GS_PAUSE,
	GS_BATTLE,
	GS_BATTLETRANSITION,
	GS_TITLE,
	GS_MAINMENU,
	GS_SAVELOADMENU,
	GS_MENUTRANSITION,
	GS_LOADING,
	GS_SHOWSCENE,
	GS_MERCHANT,
	GS_DEBUG,
	GS_NAMESELECT
}
